### ISSUE TITLE
ModuleNotFoundError: No module named 'learner'

### ISSUE THREAD

**Issue by zzxzzt333** [dongzelian/T-NAS#3]
cant find learner.py file in dir,so that the project does not work properly,
can you give me this file by email(1580335323@qq.com) ，thanks?

**Comment by dongzelian** [comment]
@zzxzzt333 learner.py file has been uploaded.

**Comment by zzxzzt333** [comment]
&nbsp;I'm really bothering you，but when i ran the new projrct，, I found another error(No module named 'operations').Could you upload operations.py,thanks?&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dongzelian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 晚上8:49
收件人:&nbsp;"dongzelian/T-NAS"<T-NAS@noreply.github.com&gt;;
抄送:&nbsp;"1580335323"<1580335323@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzelian/T-NAS] ModuleNotFoundError: No module named 'learner' (#3)





 
@zzxzzt333 learner.py file has been uploaded.

**Comment by dongzelian** [comment]
Finished

**Comment by zzxzzt333** [comment]
sorry bother you again.When i ran the new projrct，I found some problems.Project is missing files(meta_architect.py,darts_architect.py，meta_nas_train.py) and&nbsp;genotypes.py do not include PRIMITIVES, LSTM_PRIMITIVES, Genotype function.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"dongzelian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 晚上11:38
收件人:&nbsp;"dongzelian/T-NAS"<T-NAS@noreply.github.com&gt;;
抄送:&nbsp;"1580335323"<1580335323@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzelian/T-NAS] ModuleNotFoundError: No module named 'learner' (#3)





 
Finished

**Comment by dongzelian** [comment]
Solved.

**Comment by zzxzzt333** [comment]
Had run through the project,thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1580335323"                                                                                    <1580335323@qq.com&gt;;
发送时间:&nbsp;2020年6月25日(星期四) 上午8:45
收件人:&nbsp;"dongzelian/T-NAS"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [dongzelian/T-NAS] ModuleNotFoundError: No module named 'learner' (#3)



sorry bother you again.When i ran the new projrct，I found some problems.Project is missing files(meta_architect.py,darts_architect.py，meta_nas_train.py) and genotypes.py do not include PRIMITIVES, LSTM_PRIMITIVES, Genotype function.



------------------ 原始邮件 ------------------
发件人:&nbsp;"dongzelian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 晚上11:38
收件人:&nbsp;"dongzelian/T-NAS"<T-NAS@noreply.github.com&gt;;
抄送:&nbsp;"1580335323"<1580335323@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [dongzelian/T-NAS] ModuleNotFoundError: No module named 'learner' (#3)





 
Finished
