### ISSUE TITLE
Problem about the training for the task-specific  architecture.

### ISSUE THREAD

**Issue by bansheng** [dongzelian/T-NAS#4]
hi, i have viewed the code, but i have some questions about the settings of the training for the task-specific  architecture. Since the model have seen specific the test task（like 5 test classes) T while updating the Theta, why the model still use the whole meta test tasks (only 20 test classes) set for evaluation? I think it is a data leak. Could you explain about it?
[https://github.com/dongzelian/T-NAS/blob/master/train_tnas_miniimagenet.py](https://github.com/dongzelian/T-NAS/blob/master/train_tnas_miniimagenet.py

**Comment by dongzelian** [comment]
@bansheng In `train_tnas_miniimagenet.py` file, we use data in the support set in meta test to update theta and evaluate it in the query set. In the meta-learning paradigm, it is not the data leak. 
![20200929232516](https://user-images.githubusercontent.com/18697292/94579495-7a553600-02ab-11eb-9ff2-d8d81fa41871.png)

Best.
