### ISSUE TITLE
Problem about train_tnas_from_scratch

### ISSUE THREAD

**Issue by dubuqianxing** [dongzelian/T-NAS#5]
Dear Dongze Lian:
     Sorry to be a bother. I am a Grade-One graduate student from NWPU, your excellent work has inspired me a lot. Thank you! However, I have met some problems when I reappeared your results.
     i )  For part of AutoMAML, my results is 49.44% for 1-shot and 61.96% for 5-shot, which is about 2 percent below your result, can you give me some suggestions about the super-parameters' value? 
     ii ) For part of 'train_tnas_from_scrach', there lost some file(such as 'MiniImagenet_task.py' and 'meta_nas_train.py'), can you send for me? Thank you, my email address is dubuqianxing@mail.nwpu.edu.cn
     I will be appreciated for your reply, thank you very much!
                                                                                                                                                                    Gaoyitao

**Comment by dongzelian** [comment]
@dubuqianxing Thank you for your attention. 
i) Do you evaluate in test set? The code in `train_auto_maml_miniimagenet.py` is based on the validation set. You need to pick the best model in the validation set and evaluate it in the test set. 
![20200929220900](https://user-images.githubusercontent.com/18697292/94570374-5f7dc400-02a1-11eb-87e7-d00ee774040a.png)

ii) I have uploaded both files. 

Best, 
Dongze
